/**
 * Firebase Realtime Database Data Models for HyFePoul
 *
 * These models correspond strictly to the Checkpoint 5B schema.
 */

/**
 * The core physical state of the Arduino/ESP32 hardware device.
 */
export interface RTDBDeviceState {
  feedWeightGrams: number;
  targetFeedGrams: number;
  hopperLevelPercent: number;
  waterLow: boolean;
  waterHigh: boolean;
  pumpActive: boolean;
  feedingActive: boolean;
  emergencyStopActive: boolean;
  timestamp: number; // UTC timestamp generated by device
}

/**
 * Represents the top-level device object in /devices/{deviceId}
 */
export interface RTDBDevice {
  ownerId: string | null;       // The human user Firebase Auth UID
  deviceAuthUid: string | null; // The ESP32's Firebase Auth UID
  status: 'online' | 'offline'; // Device connection status
  lastHeartbeat: number;        // UTC timestamp
  state?: RTDBDeviceState;      // Current state (optional if not yet reported)
}

/**
 * A historical snapshot of the device state stored in /systemData/{deviceId}/{pushId}
 */
export interface RTDBSystemDataSnapshot extends RTDBDeviceState {
  // Same exact properties as RTDBDeviceState, representing a fixed point in time.
}

export type RTDBAlertType = 'LOW_FEED' | 'LOW_WATER' | 'WATER_PUMP_TIMEOUT' | 'EMERGENCY_STOP' | 'DEVICE_OFFLINE';

/**
 * An actionable alert/event generated by the device, stored in /alerts/{deviceId}/{pushId}
 */
export interface RTDBAlert {
  eventId: string;
  name: RTDBAlertType;
  timestamp: number;
  resolved: boolean;
}

/**
 * Temporary claim request object used during the 2-step device claiming process
 * Stored in /claimRequests/{deviceId}
 */
export interface RTDBClaimRequest {
  uid: string; // The human user's Firebase Auth UID
  pin: string; // The plaintext setup PIN provided by the user
}
